### ISSUE TITLE
WorldEdit Compatiability

### ISSUE THREAD

**Issue by nthnlws** [VelizarBG/suggestion-tweaker#2]
Having WorldEdit and this mod running at the same time causes Worldedit commands to not autofill. 

To replicate: install both mods and type "//replace whi"
Expected behavior "//replace whi**te_concrete**" Bold characters should be suggested for autofill

**Comment by VelizarBG** [comment]
I couldn't reproduce this in singleplayer and multiplayer on 1.18.2 with WE 7.2.10 and Suggestion Tweaker 1.2.0. If you still have this issue I'd recommend specifying the environment in greater detail.

**Comment by ChristopherHaws** [comment]
I have this same problem. Here are the mods I have installed: https://github.com/ChristopherHaws/mc-craftersmc-modpack/tree/41dbffc63638b5df151b84fc70227152126a3274/mods

I am running in server/client mode through a velocity proxy with:
- Minecraft 1.19.2
- Fabric 0.14.10
- Velocity 3.1.1

If I get a chance I will see if I can break it down into a minimum list of mods to repro.
