### ISSUE TITLE
Crash with Item Suggestions Not Require Mod Name

### ISSUE THREAD

**Issue by Felix14-v2** [VelizarBG/suggestion-tweaker#3]
Game crashes during the launch:
[latest.log](https://github.com/VelizarBG/suggestion-tweaker/files/8995850/latest.log)

**Info**
- Windows 10
- Minecraft 1.19
- Fabric Loader 0.14.7
- Suggestion Tweaker 1.2.1
- Item Suggestions Not Require Mod Name 1_03

**Additional**
https://github.com/RealRTTV/item-suggestions-not-require-mod-name/issues/1

**Comment by VelizarBG** [comment]
This is not a conflict I'm willing to resolve as you don't need the other mod if you've already got this one; it does what the other mod does.
