### ISSUE TITLE
Performance impact on filtering

### ISSUE THREAD

**Issue by itsdinkd** [VelizarBG/suggestion-tweaker#4]
1.19.2

When using with a large modpack, like mine, Another Quality Modpack 2, when you type a command such a /give and get to the item name argument, it takes about 4-5 seconds before it shows the items popup. I imagine its because this mod is trying to collect everything. 

I believe there could be room for improvement on this so I am here to report it.

Steps to reproduce:
1. Download AQM2 
2. Run /give @p 
3. See delay when you get to the item argument

**Comment by VelizarBG** [comment]
Hi. Thanks to the spark mod I was able to pinpoint the actual cause of this issue. It evidently comes from Emojiful's code to parse emojis in chat. I don't know what could be done about that so I'd recommend taking this situation to them. (In fact it seems it already has been InnovativeOnlineIndustries/Emojiful#77.) Any lag one experiences when writing a command after removing Emojiful is caused mostly by the sheer size of the suggestions available and the resources required to sort them alphabetically each and every time(by vanilla, not ST). Even if one removes ST there won't be a noticeable reduction in the size of lag spikes.

Here are the steps in case one wants to reproduce the profiling run:
1. Join a world and wait for fps to stabilize
2. Run `/spark profiler start --only-ticks-over 50 --thread render thread`
3. Trigger a lag spike using `/scoreboard objectives add a `
4. After the lag spike is over run `/spark profiler stop`

**Comment by itsdinkd** [comment]
Wow, you are right. it was emojiful. thank you. I tried using spark before but I didn't know about the thread feature + creating an intentional lag spike
