### ISSUE TITLE
1.19.4 Fabric crash - Could not execute entrypoint stage 'wait' due to errors

### ISSUE THREAD

**Issue by YTFrost** [VelizarBG/suggestion-tweaker#5]
Hello. I tried installing the mod on fabric 1.19.4 -  0.14.18,  but the mod throws an error unfortunately. Here's the crash report:

https://mclo.gs/GznWikO#L200

Also linking it as a file
[crash log.txt](https://github.com/VelizarBG/suggestion-tweaker/files/11225343/crash.log.txt)

**Comment by VelizarBG** [comment]
Hi. This happens because you haven't installed the required dependency [Cloth Config API](https://www.curseforge.com/minecraft/mc-mods/cloth-config). I will push an update in a bit to explicitly mention when one lacks it.

**Comment by YTFrost** [comment]
Hmm. If you look at the logs, you can see I have Cloth config installed

**Comment by VelizarBG** [comment]
Ah, yeah, you do. But it's for Forge.

**Comment by YTFrost** [comment]
Oh... yeah you're right. The crash is gone now, sorry for that hah

**Comment by VelizarBG** [comment]
All good. Thank you for reminding me to fix this properly.
